import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  ChevronRight,
  Award,
  CheckCircle,
  XCircle,
  Menu
} from 'lucide-react';
import { getCurrentUser } from '@/lib/auth';
import LearningSidebar from '@/components/LearningSidebar';
import { evaluateQuizAnswers } from '@/integrations/llm-engine/client';

interface QuizQuestion {
  id: string;
  question_text: string;
  expected_answer: string;
  points: number;
  order_index: number;
  options?: string[]; // For multiple choice questions
}

const Quiz: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const location = useLocation();
  const navigate = useNavigate();
  
  // Get quiz data from location state
  const { questions, moduleId, moduleTitle } = location.state || {};
  
  const [user, setUser] = useState<any>(null);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [userAnswers, setUserAnswers] = useState<Record<string, string>>({});
  const [submitted, setSubmitted] = useState(false);
  const [evaluationResult, setEvaluationResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarLocked, setSidebarLocked] = useState(false);

  const handleSidebarLockChange = (locked: boolean) => {
    setSidebarLocked(locked);
    localStorage.setItem('sidebarLocked', locked.toString());
  };

  useEffect(() => {
    const savedLockedState = localStorage.getItem('sidebarLocked');
    if (savedLockedState === 'true') {
      setSidebarLocked(true);
    }
    
    const checkAuth = async () => {
      try {
        const currentUser = await getCurrentUser();
        if (!currentUser) {
          navigate("/auth");
          return;
        }
        setUser(currentUser);
      } catch (err) {
        setError('Authentication error');
      }
    };

    checkAuth();
  }, [navigate]);

  // Redirect if no quiz data
  useEffect(() => {
    if (!questions || !moduleId) {
      navigate('/courses');
    }
  }, [questions, moduleId, navigate]);

  const currentQuestion = questions?.[currentQuestionIndex];

  // Function to generate multiple choice options for a question
  const generateOptions = (question: QuizQuestion) => {
    // In a real implementation, these would be generated by the LLM
    // For now, we'll create sample options
    const sampleOptions: Record<string, string[]> = {
      1: [
        "Visit the e-SW system website and create an account",
        "Call the customs office directly",
        "Send an email to the support team",
        "Visit a physical customs office"
      ],
      2: [
        "Provide business type, size, and primary activities",
        "Only provide the business name",
        "Upload financial statements",
        "Submit tax returns"
      ],
      3: [
        "Link existing customs account with new e-SW profile",
        "Create a new customs account",
        "Delete the old account",
        "Ignore the customs account"
      ],
      4: [
        "Submit through the unified platform with automatic routing",
        "Submit to each agency separately",
        "Call each agency directly",
        "Send documents by mail"
      ],
      5: [
        "Upload all required documents as specified",
        "Only upload the invoice",
        "Upload documents later",
        "Send documents by fax"
      ]
    };
    
    return sampleOptions[question.order_index] || [
      "Option A",
      "Option B", 
      "Option C",
      "Option D"
    ];
  };

  const handleAnswerChange = (questionId: string, answer: string) => {
    setUserAnswers(prev => ({
      ...prev,
      [questionId]: answer
    }));
  };

  const handleNext = () => {
    if (currentQuestionIndex < (questions?.length || 0) - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
    }
  };

  const handlePrevious = () => {
    if (currentQuestionIndex > 0) {
      setCurrentQuestionIndex(prev => prev - 1);
    }
  };

  const handleSubmit = async () => {
    if (!questions || !moduleId) return;
    
    setLoading(true);
    try {
      // Evaluate answers using the LLM engine
      const result = await evaluateQuizAnswers(moduleId, questions, userAnswers);
      
      if (result) {
        setEvaluationResult(result);
        setSubmitted(true);
      } else {
        setError('Failed to evaluate quiz');
      }
    } catch (err) {
      console.error('Failed to evaluate quiz:', err);
      setError('Failed to evaluate quiz');
    } finally {
      setLoading(false);
    }
  };

  if (!questions || !moduleId) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
      </div>
    );
  }

  if (submitted && evaluationResult) {
    return (
      <div className="flex">
        <Button
          variant="ghost"
          size="icon"
          className="fixed top-4 left-4 z-50 lg:hidden"
          onClick={() => setSidebarOpen(!sidebarOpen)}
        >
          <Menu className="h-6 w-6" />
        </Button>
        
        <LearningSidebar 
          activeSection="courses"
          locked={sidebarLocked}
          onLockChange={handleSidebarLockChange}
          onSectionChange={() => setSidebarOpen(false)}
        />
        <div className="container mx-auto py-8 flex-1 lg:ml-64">
          <div className="mb-6">
            <Button 
              variant="ghost" 
              className="mb-4"
              onClick={() => navigate('/courses')}
            >
              <ChevronRight className="h-4 w-4 rotate-180 mr-2" />
              Back to Courses
            </Button>
            
            <h1 className="text-3xl font-bold text-gray-900">Assessment Results</h1>
            <p className="text-muted-foreground mt-2">{moduleTitle}</p>
          </div>

          <Card className="max-w-2xl mx-auto">
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <span>Assessment Results</span>
                {evaluationResult.passed ? (
                  <CheckCircle className="h-8 w-8 text-green-500" />
                ) : (
                  <XCircle className="h-8 w-8 text-red-500" />
                )}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-center py-6">
                <div className={`text-4xl font-bold ${evaluationResult.passed ? 'text-green-600' : 'text-red-600'}`}>
                  {evaluationResult.score}%
                </div>
                <p className="text-muted-foreground mt-2">
                  {evaluationResult.passed ? 'Congratulations! You passed the assessment.' : 'You need to score at least 90% to pass.'}
                </p>
                
                {evaluationResult.passed && (
                  <div className="mt-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
                    <div className="flex items-center justify-center gap-2 mb-2">
                      <Award className="h-6 w-6 text-blue-500" />
                      <h3 className="font-medium text-blue-900">Certificate Earned</h3>
                    </div>
                    <p className="text-sm text-blue-800">
                      You've successfully completed the {moduleTitle} course and earned a certificate.
                    </p>
                    <Button 
                      className="mt-4"
                      onClick={() => navigate('/certificates')}
                    >
                      View Certificate
                    </Button>
                  </div>
                )}
              </div>
              
              <Separator className="my-6" />
              
              <div className="space-y-4">
                <h3 className="font-medium">Detailed Feedback</h3>
                {evaluationResult.detailed_feedback.map((feedback: any, index: number) => (
                  <div key={index} className="p-3 bg-muted rounded-lg">
                    <div className="flex items-center justify-between">
                      <span className="font-medium">Question {index + 1}</span>
                      <Badge variant={feedback.score > 0 ? "default" : "destructive"}>
                        {Math.round(feedback.score * 100)}% Score
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">{feedback.feedback}</p>
                  </div>
                ))}
              </div>
              
              <div className="flex gap-3 mt-6">
                <Button 
                  variant="outline" 
                  onClick={() => navigate(`/course/${moduleId}`)}
                >
                  Review Course
                </Button>
                {!evaluationResult.passed && (
                  <Button onClick={() => window.location.reload()}>
                    Retake Assessment
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="flex">
      <Button
        variant="ghost"
        size="icon"
        className="fixed top-4 left-4 z-50 lg:hidden"
        onClick={() => setSidebarOpen(!sidebarOpen)}
      >
        <Menu className="h-6 w-6" />
      </Button>
      
      <LearningSidebar 
        activeSection="courses"
        locked={sidebarLocked}
        onLockChange={handleSidebarLockChange}
        onSectionChange={() => setSidebarOpen(false)}
      />
      <div className="container mx-auto py-8 flex-1 lg:ml-64">
        <div className="mb-6">
          <Button 
            variant="ghost" 
            className="mb-4"
            onClick={() => navigate(`/course/${moduleId}`)}
          >
            <ChevronRight className="h-4 w-4 rotate-180 mr-2" />
            Back to Course
          </Button>
          
          <h1 className="text-3xl font-bold text-gray-900">Assessment</h1>
          <p className="text-muted-foreground mt-2">{moduleTitle}</p>
        </div>

        <Card className="max-w-2xl mx-auto">
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <span>Question {currentQuestionIndex + 1} of {questions.length}</span>
              <Badge variant="secondary">
                {currentQuestion?.points} point{currentQuestion?.points !== 1 ? 's' : ''}
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="mb-6">
              <h2 className="text-xl font-medium mb-4">{currentQuestion?.question_text}</h2>
              
              {/* Multiple Choice Options */}
              <div className="space-y-3">
                {generateOptions(currentQuestion).map((option, index) => (
                  <div 
                    key={index}
                    className={`p-3 border rounded-md cursor-pointer transition-colors ${
                      userAnswers[currentQuestion?.id] === option 
                        ? 'border-primary bg-primary/10' 
                        : 'border-gray-200 hover:border-gray-300'
                    }`}
                    onClick={() => handleAnswerChange(currentQuestion?.id, option)}
                  >
                    <div className="flex items-center">
                      <div className={`flex-shrink-0 w-5 h-5 rounded-full border mr-3 flex items-center justify-center ${
                        userAnswers[currentQuestion?.id] === option 
                          ? 'border-primary bg-primary' 
                          : 'border-gray-300'
                      }`}>
                        {userAnswers[currentQuestion?.id] === option && (
                          <div className="w-2 h-2 rounded-full bg-white"></div>
                        )}
                      </div>
                      <span>{option}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="flex justify-between">
              <Button 
                variant="outline" 
                onClick={handlePrevious}
                disabled={currentQuestionIndex === 0}
              >
                Previous
              </Button>
              
              {currentQuestionIndex < questions.length - 1 ? (
                <Button 
                  onClick={handleNext}
                  disabled={!userAnswers[currentQuestion?.id]}
                >
                  Next
                </Button>
              ) : (
                <Button 
                  onClick={handleSubmit}
                  disabled={loading || !userAnswers[currentQuestion?.id]}
                >
                  {loading ? 'Submitting...' : 'Submit Assessment'}
                </Button>
              )}
            </div>
            
            {error && (
              <div className="mt-4 p-3 bg-red-50 text-red-700 rounded-md">
                {error}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Quiz;